Handle exception in depcheck
https://github.com/oaubert/advene/actions/runs/10583260889/job/29324863836 failed with

  File "D:/a/advene/advene/dev/win_installer/misc/depcheck.py", line 28, in _get_shared_libraries
    repo.require(namespace, version, 0)
gi.repository.GLib.GError: g-irepository-error-quark: Typelib file for namespace 'GIRepository', version '3.0' not found (0)

which is strange since GIRepository is 2.0.